
INFO6105 Instructor: Dr. Handan Liu

Homework 1  

Grading: total 100 points.


In [20]:
import numpy as np
import random

In [5]:
array= np.array([1, 2, 3,])
print(array)

[1 2 3]


In [7]:
x =[1, 2] 
np.asarray(x)

array([1, 2])

In [16]:
np.ones((3, 2), dtype=np.float64)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.full((2,5), (10))

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [7]:
np.arange(2,102,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [10]:
arr2=np.zeros(10)
print("array of 10 zeros",arr2)
arr3=np.ones(10)*5
print("array of 10 fives",arr3)

array of 10 zeros [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
array of 10 fives [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [12]:
np.random.rand(3,3)

array([[0.25011376, 0.94556367, 0.8696893 ],
       [0.83551153, 0.04813807, 0.7861268 ],
       [0.59187794, 0.64999567, 0.57147363]])

In [26]:
np.arange(10,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [41]:
x = np.zeros((4, 4))
x[::2,1::2] = 1
x[1::2, ::2]=1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [20]:
# 1)
np.random.seed(10)
np.random.randint(6,size = 5)



array([1, 5, 4, 0, 1])

In [217]:
#2)
np.random.uniform(0,1, size = (3,2))

array([[0.61261987, 0.13457199],
       [0.86557574, 0.67588463],
       [0.97937298, 0.38268732]])

In [39]:
#3)
np.random.randint(0, 4, size =(3,2))

array([[2, 1],
       [0, 0],
       [3, 2]])

In [15]:
x = np.arange(1, 10)
print(x)
np.split(x, [4, 6])

[1 2 3 4 5 6 7 8 9]


[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

In [56]:
x = np.arange(0, 16).reshape(4,4)
print(x)
np.hsplit(x, 2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [225]:
print("(1)",x[0:2,1:3])
print("(2)",x[1:2, 0:1])

(1) [[10 15]
 [25 30]]
(2) [[20]]


In [220]:
x=np.arange(5,50,5).reshape(3,3)
x

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [133]:
x=np.arange(1,7).reshape(2,3)
y=np.arange(7,13).reshape(2,3)
print("x=",x)
print("y=",y)
np.concatenate((x, y), axis=1)

x= [[1 2 3]
 [4 5 6]]
y= [[ 7  8  9]
 [10 11 12]]


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [142]:
x=np.array([3, 6, 9, 25, 10, 8])
print("orignal array",x)
print("answer",x[1:])

orignal array [ 3  6  9 25 10  8]
answer [ 6  9 25 10  8]


In [144]:
x=np.array([3, 6, 9, 25, 10, 8])
print("orignal array",x)
print("answer",x[:5])

orignal array [ 3  6  9 25 10  8]
answer [ 3  6  9 25 10]


In [171]:
x=np.array([3, 6, 9, 25, 10, 8])
print("orignal array",x)
print("answer",x[::2])

orignal array [ 3  6  9 25 10  8]
answer [ 3  9 10]


In [168]:
x=np.array([3, 6, 9, 25, 10, 8])
print("orignal array",x)
print("answer",x[:5])

orignal array [ 3  6  9 25 10  8]
answer [ 3  6  9 25 10]


In [145]:
np.flip(x)

array([ 8, 10, 25,  9,  6,  3])

In [162]:
x=np.arange(0,32).reshape(8,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [163]:
x[:1, 2:3] =0
print(x)

[[ 0  1  0  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [167]:
x=np.arange(0,32).reshape(8,4)
print(x[:9,1:2])


[[ 1]
 [ 5]
 [ 9]
 [13]
 [17]
 [21]
 [25]
 [29]]


In [170]:
x=np.arange(0,32).reshape(8,4)
print(x[:3, :3])

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [199]:
x = np.random.rand(1000)
a=np.round(np.mean(x),5)
print("Average of the element is:",a)
b=np.around(np.std(x),5)
print("Standard deviation of the array elements:",b)
c=np.around(np.var(x),5)
print("Variance of the array elements:",c)


Average of the element is: 0.49466
Standard deviation of the array elements: 0.28948
Variance of the array elements: 0.0838


In [226]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
print(a)
print(b)
print(a +b[:, np.newaxis])

[ 0. 10. 20. 30.]
[1. 2. 3.]
[[ 1. 11. 21. 31.]
 [ 2. 12. 22. 32.]
 [ 3. 13. 23. 33.]]


In [230]:
x = np.arange(4)
y = np.ones(5).reshape(5,1)
print(x,"\n",y)
print(x+ y)

[0 1 2 3] 
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [270]:
x=np.arange(1,7).reshape(1,6)
y=np.arange(1,7).reshape(6,1)
print(x*y)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [260]:
for i in range(1, 7):
    for j in range(1,7):
        print(i*j, end="\t")
    print()

1	2	3	4	5	6	
2	4	6	8	10	12	
3	6	9	12	15	18	
4	8	12	16	20	24	
5	10	15	20	25	30	
6	12	18	24	30	36	


In [305]:
x=np.random.rand(10,3)
print(x)

[[0.8052232  0.52164715 0.90864888]
 [0.31923609 0.09045935 0.30070006]
 [0.11398436 0.82868133 0.04689632]
 [0.62628715 0.54758616 0.819287  ]
 [0.19894754 0.8568503  0.35165264]
 [0.75464769 0.29596171 0.88393648]
 [0.32551164 0.1650159  0.39252924]
 [0.09346037 0.82110566 0.15115202]
 [0.38411445 0.94426071 0.98762547]
 [0.45630455 0.82612284 0.25137413]]


In [313]:
y=np.mean(x,axis=0)
print(y)


[0.4077717  0.58976911 0.50938022]


In [311]:
z=x-y
print(z)

[[ 0.39745149 -0.06812196  0.39926866]
 [-0.08853561 -0.49930976 -0.20868017]
 [-0.29378734  0.23891222 -0.46248391]
 [ 0.21851544 -0.04218295  0.30990677]
 [-0.20882416  0.26708119 -0.15772758]
 [ 0.34687599 -0.2938074   0.37455626]
 [-0.08226007 -0.42475321 -0.11685098]
 [-0.31431133  0.23133655 -0.3582282 ]
 [-0.02365725  0.3544916   0.47824525]
 [ 0.04853284  0.23635373 -0.25800609]]


In [312]:
np.mean(z)

8.881784197001253e-17